HRMS/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout_then_login
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),
    url(r'^areas/', include('apps.areas.urls', namespace='areas')),
    url(r'^vacaciones/', include('apps.vacaciones.urls', namespace='vacaciones')),
]

if settings.DEBUG is True:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/areas/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url, include

from apps.areas.views import AreaCreate, AreaList, PersonaArea
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^nueva_area/', login_required(AreaCreate.as_view()), name='nueva_area'),
    url(r'^listado_areas/', login_required(AreaList.as_view()), name='listado_areas'),
    url(r'^persona_areas/(?P<ar_id>\d+)/$', login_required(PersonaArea), name='persona_areas'),
]

apps/areas/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Area(models.Model):
    nombre_area = models.CharField(max_length = 30)
    clave_area = models.CharField(max_length = 12)
    descripcion = models.TextField()

    def __unicode__(self):
        return self.nombre_area

apps/areas/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django import forms
from apps.areas.models import Area

class AreaForm(forms.ModelForm):
    class Meta:
        model = Area

        fields = [
            'nombre_area',
            'clave_area',
            'descripcion',
        ]

        labels = {
            'nombre_area':'Nombre del Area',
            'clave_area':'Clave del Area',
            'descripcion':'Descripcion',
        }

        widgets = {
            'nombre_area':forms.TextInput(attrs={'class':'form-control'}),
            'clave_area':forms.TextInput(attrs={'class':'form-control'}),
            'descripcion':forms.TextInput(attrs={'class':'form-control'}),
        }

apps/areas/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView
from django.core.urlresolvers import reverse_lazy

from apps.areas.models import Area
from apps.areas.forms import AreaForm

from apps.personas.models import Persona

# Create your views here.
#Vistas del modelo area

class AreaCreate(CreateView):
    model = Area
    form_class = AreaForm
    template_name = 'areas/area_form.html'
    success_url = reverse_lazy('areas:listado_areas') #esta url se debe cambiar hacia el listado

class AreaList(ListView):
    model = Area
    template_name = 'areas/area_list.html'

def PersonaArea(request, ar_id):
    persona = Persona.objects.distinct().filter(areas=ar_id)
    template = 'areas/area_persona.html'
    context = {'personas':persona}
    return render(request, template, context)

templates/areas/area_form.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Areas</a>
  </li>
  <li class="breadcrumb-item active">Nueva área</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  {# <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt explicabo vero veritatis ab fugit? Excepturi, illum possimus? Sunt, nobis consequatur sapiente repellendus soluta sed corrupti doloremque adipisci non, officiis in?</span>#}
  <div class="card-header">
    <i class="fa fa-sitemap"></i>
    Nueva área
  </div>
  <div class="card-body">
    <form method="post" class="form-group">
      {% csrf_token %}

      {{ form.as_p }}

      <br>
      <div class="row">
        <div class="form-group col-md-4 ml-auto">
          <button type="submit" class="btn btn-success btn-block">Crear área</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/areas/area_list.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Areas</a>
  </li>
  <li class="breadcrumb-item active">Listado de areas</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-table"></i>
    Listado de áreas
  </div>
  <div class="card-body">
    <div class="table-responsive">
      {% if not object_list %}
      <h4>No hay empleados registrados</h4>
      {% else  %}
      <table class="table table-bordered" width="100%" id="" cellspacing="0">
        <thead>
          <tr>
          <th>#</th>
          <th>Id Áreas</th>
          <th>Nombre del área</th>
          <th>Descripción</th>
          <th>Información</th>
          </tr>
        </thead>

        <tbody>
          {% for item in object_list %}
          <tr>
            <td>{{item.id}}</td>
            <td>{{item.clave_area}}</td>
            <td>{{item.nombre_area}}</td>
            <td>{{item.descripcion}}</td>
            <td>
              <a href="{% url 'areas:persona_areas' item.id %}" class="btn btn-success">Personal</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/areas/area_persona.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Áreas</a>
  </li>
  <li class="breadcrumb-item active">Personal por Áreas</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-table"></i>
    Listado de personal
  </div>
  <div class="card-body">
    <div class="table-responsive">
      {% if not personas %}
      <h4>No hay empleados registrados</h4>
      {% else  %}
      <table class="table table-bordered" width="100%" id="dataTable" cellspacing="0">
        <thead>
          <tr>
            <th>Id Persona</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Fecha de Ingreso</th>
            <th>Area</th>
          </tr>
        </thead>

        <tbody>
          {% for item in personas %}
          <tr>
            <td>{{item.id_persona}}</td>
            <td>{{item.nombre}}</td>
            <td>{{item.apellido_paterno}} {{item.apellido_materno}}</td>
            <td>{{item.fecha_ingreso}}</td>
            <td>{{item.areas.nombre_area}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}