HRMS/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout_then_login
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),
    url(r'^areas/', include('apps.areas.urls', namespace='areas')),
    url(r'^vacaciones/', include('apps.vacaciones.urls', namespace='vacaciones')),
]

if settings.DEBUG is True:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/areas/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url, include

from apps.areas.views import AreaCreate, AreaList, PersonaArea
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^nueva_area/', login_required(AreaCreate.as_view()), name='nueva_area'),
    url(r'^listado_areas/', login_required(AreaList.as_view()), name='listado_areas'),
    url(r'^persona_areas/(?P<ar_id>\d+)/$', login_required(PersonaArea), name='persona_areas'),
]

apps/personas/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url, include
from apps.personas.views import PersonaCreate, PersonaList, PersonaUpdate, PersonaDelete, PersonaInfo,\
PersonaInicio, PersonaFormato, PersonaListInactive, PersonaInactivePdf, PersonaFormatoBaja

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^inicio_persona$', login_required(PersonaInicio), name='inicio_persona'),
    url(r'^nueva_persona$', login_required(PersonaCreate.as_view()), name='nueva_persona'),
    url(r'^listado_persona$', login_required(PersonaList.as_view()), name='listado_persona'), #activos
    url(r'^baja_persona$', login_required(PersonaListInactive.as_view()), name='baja_persona'), #inactivos
    url(r'^baja_list$', login_required(PersonaInactivePdf), name='baja_list'), #inactivosPDF
    url(r'^info_persona/(?P<pk>\d+)$', login_required(PersonaInfo), name='info_persona'),
    url(r'^persona_formato/(?P<pk>\d+)$', login_required(PersonaFormato), name='persona_formato'),
    url(r'^persona_formato_baja/(?P<pk>\d+)$', login_required(PersonaFormatoBaja), name='persona_formato_baja'), #PDF
    # url(r'^vacaciones_hist/(?P<pk>\d+)$', PersonaVacacionesHist, name='vacaciones_hist'),
    # url(r'^persona_vacaciones/(?P<pk>\d+)$', login_required(PersonaVacaciones), name='persona_vacaciones'),
    url(r'^editar_persona/(?P<pk>\d+)$', login_required(PersonaUpdate.as_view()), name='editar_persona'),
    url(r'^eliminar_persona/(?P<pk>\d+)$', login_required(PersonaDelete.as_view()), name='eliminar_persona'),
]

apps/vacaciones/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url, include
from apps.vacaciones.views import AsignaVacaciones, VacacionesPersona, AsignaPermisos, PersonaVacacionesHist,\
PersonaPermisosHist, VacacionesList, PermisosList, VacacionesHist, PermisosHist

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^asignar_vacaciones/(?P<pk>\d+)$', login_required(AsignaVacaciones), name='asignar_vacaciones'),
    url(r'^info_persona/(?P<pk>\d+)$', login_required(VacacionesPersona), name='info_persona'),
    url(r'^vacaciones_hist/(?P<pk>\d+)$', login_required(PersonaVacacionesHist), name='vacaciones_hist'),
    url(r'^vacaciones_list$', login_required(VacacionesList.as_view()), name='vacaciones_list'),
    url(r'^vacaciones_historial$', login_required(VacacionesHist), name='vacaciones_historial'),

    #Permisos
    url(r'^asignar_permisos/(?P<pk>\d+)$', login_required(AsignaPermisos), name='asignar_permisos'),
    url(r'^permisos_hist/(?P<pk>\d+)$', login_required(PersonaPermisosHist), name='permisos_hist'),
    url(r'^permisos_list$', login_required(PermisosList.as_view()), name='permisos_list'),
    url(r'^permisos_historial$', login_required(PermisosHist), name='permisos_historial'),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}
    <title>HRMS</title>
    {% endblock %}

    {% block estilos %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Plugin CSS -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    {% endblock %}
  </head>

  <body class="fixed-nav sticky-footer bg-dark" id="page-top">

    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="#">Sistema Administrador de Recursos Humanos</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse"  href="#collapseMulti2" data-parent="#exampleAccordion">
              <i class="fa fa-fw fa-sitemap"></i>
              <span class="nav-link-text">Areas</span>
            </a>
            <ul class="sidenav-third-level collapse" id="collapseMulti2">
              <li>
                <a href="{% url 'areas:nueva_area' %}">Nueva área</a>
              </li>
              <li>
                <a href="{% url 'areas:listado_areas'%}">Listado de áreas</a>
              </li>
            </ul>
          </li>

          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
              <i class="fa fa-fw fa-users"></i>
              <span class="nav-link-text">Personal</span>
            </a>
            <ul class="sidenav-second-level collapse" id="collapseComponents">
              <li>
                <a href="{% url 'personas:nueva_persona' %}">Alta de personal</a>
              </li>
              <li>
                <a href="{% url 'personas:listado_persona' %}">Listado de personal</a>
              </li>
            </ul>
          </li>

          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
              <i class="fa fa-list" aria-hidden="true"></i>
              <span class="nav-link-text">Listados</span>
            </a>
            <ul class="sidenav-second-level collapse" id="collapseExamplePages">
              <li>
                <a href="{% url 'vacaciones:vacaciones_list' %}">Historial de Vacaciones</a>
              </li>
              <li>
                <a href="{% url 'vacaciones:permisos_list' %}">Historial de Permisos</a>
              </li>
              <li>
                <a href="{% url 'personas:baja_persona' %}">Historial de Bajas</a>
              </li>
            </ul>
          </li>
          <!-- <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
              <i class="fa fa-fw fa-money"></i>
              <span class="nav-link-text">Pagos</span>
            </a>
            <ul class="sidenav-second-level collapse" id="collapseMulti">
              <li>
                <a href="#">Second Level Item</a>
              </li>
              <li>
                <a href="#">Second Level Item</a>
              </li>
            </ul>
          </li> -->
        </ul>

        <ul class="navbar-nav sidenav-toggler">
          <li class="nav-item">
            <a class="nav-link text-center" id="sidenavToggler">
              <i class="fa fa-fw fa-angle-left"></i>
            </a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
              <i class="fa fa-fw fa-sign-out"></i>
              Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    {% endblock %}

  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs -->
      {% block breadcrumb %}
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Alta de Personal</a>
        </li>
        <li class="breadcrumb-item active">Altas</li>
      </ol>
      {% endblock %}

      <!-- Area Chart Example -->
      {% block content %}
      <div class="card mb-3">
        <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt explicabo vero veritatis ab fugit? Excepturi, illum possimus? Sunt, nobis consequatur sapiente repellendus soluta sed corrupti doloremque adipisci non, officiis in?</span>
        <!--<div class="card-header">
          <i class="fa fa-users"></i>
          Formulario de altas
        </div>
        <div class="card-body">
          <form action="">
            <span>Nombre</span>
            <p>Aqui van los formularios</p>
          </form>
        </div>
        <div class="card-footer small text-muted">
          Updated yesterday at 11:59 PM
        </div> -->
      </div>
      {% endblock %}
    </div>
  </div>

  {% block footer %}
  <footer class="sticky-footer">
    <div class="container">
      <div class="text-center">
        <small>Copyright &copy; Sistema creado por Ismael Caslop</small>
      </div>
    </div>
  </footer>
  {% endblock %}

    <!-- Scroll to Top Button -->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>

    <!-- Logout Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Presiona "Salir" si estas seguro de querer cerrar tu sesión actual.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <a class="btn btn-primary" href="{% url 'logout' %}">Salir</a> <!-- login.html -->
          </div>
        </div>
      </div>
    </div>

    {% block script %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js'%}"></script>
    <!-- Custom scripts for this template -->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    {% endblock %}

    {% block extrajs %}
    {% endblock %}

  </body>

</html>