HRMS/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout_then_login
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),
    url(r'^areas/', include('apps.areas.urls', namespace='areas')),
    url(r'^vacaciones/', include('apps.vacaciones.urls', namespace='vacaciones')),
]

if settings.DEBUG is True:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/vacaciones/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url, include
from apps.vacaciones.views import AsignaVacaciones, VacacionesPersona, AsignaPermisos, PersonaVacacionesHist,\
PersonaPermisosHist, VacacionesList, PermisosList, VacacionesHist, PermisosHist

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^asignar_vacaciones/(?P<pk>\d+)$', login_required(AsignaVacaciones), name='asignar_vacaciones'),
    url(r'^info_persona/(?P<pk>\d+)$', login_required(VacacionesPersona), name='info_persona'),
    url(r'^vacaciones_hist/(?P<pk>\d+)$', login_required(PersonaVacacionesHist), name='vacaciones_hist'),
    url(r'^vacaciones_list$', login_required(VacacionesList.as_view()), name='vacaciones_list'),
    url(r'^vacaciones_historial$', login_required(VacacionesHist), name='vacaciones_historial'),

    #Permisos
    url(r'^asignar_permisos/(?P<pk>\d+)$', login_required(AsignaPermisos), name='asignar_permisos'),
    url(r'^permisos_hist/(?P<pk>\d+)$', login_required(PersonaPermisosHist), name='permisos_hist'),
    url(r'^permisos_list$', login_required(PermisosList.as_view()), name='permisos_list'),
    url(r'^permisos_historial$', login_required(PermisosHist), name='permisos_historial'),
]

apps/vacaciones/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import models
import datetime

from apps.personas.models import Persona
# Create your models here.

class Vacaciones(models.Model):
    dias_tomados = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    razon = models.CharField(max_length=50)
    observaciones = models.CharField(max_length=50)
    id_solicitante = models.CharField(max_length=13, default=0)
    personas = models.ForeignKey(Persona, null=True, blank=True)

    def __get__dias(self):
        today = datetime.date.today()
        ingreso = self.personas.fecha_ingreso

        return (today.year - ingreso.year)*10

    dias_vacaciones = property(__get__dias)

    def __get__restantes(self):
        today = datetime.date.today()
        ingreso = self.personas.fecha_ingreso
        total = (today.year - ingreso.year)*10
        restante = total - int(self.dias_tomados)

        return restante


    dias_restantes = property(__get__restantes)


class Permisos(models.Model):
    opciones = [('Económico', 'Económico'), ('Especial', 'Especial')]

    dias_tomados = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    tipo = models.CharField(max_length=50, choices=opciones)
    observaciones = models.CharField(max_length=50)
    id_solicitante = models.CharField(max_length=13, default=0)
    personas = models.ForeignKey(Persona, null=True, blank=True)

apps/vacaciones/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django import forms

from apps.vacaciones.models import Vacaciones, Permisos

class VacacionesForm(forms.ModelForm):
    class Meta:
        model = Vacaciones

        fields = [
            'dias_tomados',
            'fecha_inicio',
            'razon',
            'observaciones',
            'id_solicitante',
        ]

        labels = {
            'dias_tomados': 'Días tomados',
            'fecha_inicio': 'Fecha de inicio',
            'razon': 'Razón',
            'observaciones': 'Observaciones',
            'id_solicitante': 'Clave del solicitante'
        }

        widgets = {
            'dias_tomados': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_inicio': forms.TextInput(attrs={'class':'form-control'}),
            'razon': forms.TextInput(attrs={'class':'form-control'}),
            'observaciones': forms.TextInput(attrs={'class':'form-control'}),
            'id_solicitante': forms.TextInput(attrs={'class':'form-control'}),
        }

class PermisosForm(forms.ModelForm):
    class Meta:
        model = Permisos

        fields = [
            'dias_tomados',
            'fecha_inicio',
            'tipo',
            'observaciones',
            'id_solicitante',
        ]

        labels = {
            'dias_tomados':'Días tomados',
            'fecha_inicio':'Fecha de inicio',
            'tipo':'Tipo',
            'observaciones':'Observaciones',
            'id_solicitante':'Id Solicitante',
        }

        widgets = {
            'dias_tomados': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_inicio': forms.TextInput(attrs={'class':'form-control'}),
            'tipo': forms.Select(attrs={'class':'form-control'}),
            'observaciones': forms.TextInput(attrs={'class':'form-control'}),
            'id_solicitante': forms.TextInput(attrs={'class':'form-control'}),
        }

apps/vacaciones/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

import pdfkit
from django.template.loader import render_to_string

from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse

from apps.vacaciones.forms import VacacionesForm, PermisosForm
from apps.vacaciones.models import Vacaciones, Permisos

from apps.personas.models import Persona
from apps.areas.models import Area

# Create your views here.
#Vacaciones

class VacacionesList(ListView):
    model = Vacaciones
    template_name = 'vacaciones/vacaciones_list.html'

def AsignaVacaciones(request, pk):
    persona = Persona.objects.get(id=pk)
    if request.method == 'POST':
        form = VacacionesForm(data=request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.persona = persona
            instance.save()
        return redirect('personas:listado_persona')
    else:
        form = VacacionesForm()
    return render(request, 'vacaciones/vacaciones_form.html', {'vacaciones':form, 'personas':persona})

def VacacionesPersona(request, pk):
    personas = Persona.objects.get(id=pk)
    context = {'vacaciones':personas}
    return render(request, 'personas/persona_info.html', context)


def PersonaVacacionesHist(request, pk):
    vacaciones = Vacaciones.objects.all().filter(id_solicitante=pk)
    personas = Persona.objects.all().filter(id=pk)
    rendered = render_to_string('formatos/vacaciones_hist.html', {'personas':personas, 'vacaciones':vacaciones})
    # Create a URL of our project and go to the template route
    pdf = pdfkit.from_string(rendered, False)
    # Generate download
    response = HttpResponse(pdf, content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response

def VacacionesHist(request):
    vacaciones = Vacaciones.objects.all()
    personas = Persona.objects.all()
    rendered = render_to_string('formatos/vacaciones_solicitadas.html', {'personas':personas, 'vacaciones':vacaciones})
    # Create a URL of our project and go to the template route
    pdf = pdfkit.from_string(rendered, False)
    # Generate download
    response = HttpResponse(pdf, content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response

#Permisos

class PermisosList(ListView):
    model = Permisos
    template_name = 'vacaciones/permisos_list.html'

def AsignaPermisos(request, pk):
    persona = Persona.objects.get(id=pk)
    if request.method == 'POST':
        form = PermisosForm(data=request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.persona = persona
            instance.save()
        return redirect('personas:listado_persona')
    else:
        form = PermisosForm()
    return render(request, 'permisos/permisos_form.html', {'permisos':form, 'personas':persona})

def PersonaPermisosHist(request, pk):
    permisos = Permisos.objects.all().filter(id_solicitante=pk)
    personas = Persona.objects.all().filter(id=pk)
    rendered = render_to_string('formatos/permisos_hist.html', {'personas':personas, 'permisos':permisos})
    # Create a URL of our project and go to the template route
    pdf = pdfkit.from_string(rendered, False)
    # Generate download
    response = HttpResponse(pdf, content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response

def PermisosHist(request):
    permisos = Permisos.objects.all()
    personas = Persona.objects.all()
    rendered = render_to_string('formatos/permisos_solicitados.html', {'personas':personas, 'permisos':permisos})
    # Create a URL of our project and go to the template route
    pdf = pdfkit.from_string(rendered, False)
    # Generate download
    response = HttpResponse(pdf, content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response

templates/vacaciones/permisos_list.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Listados</a>
  </li>
  <li class="breadcrumb-item active">Permisos Solicitados</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header row">
    <div class="col-md-6"><i class="fa fa-table"></i> Listado de Permisos Solicitadas</div>
    <div class="col-md-6 offset-md-6"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><a href="{% url 'vacaciones:permisos_historial' %}"> Exportar a PDF</a></span></div>
  </div>
  
  <div class="card-body">
    <div class="table-responsive">
      {% if not object_list %}
      <h4>No hay empleados registrados</h4>
      {% else  %}
      <table class="table table-bordered" width="100%" id="dataTable" cellspacing="0">
        <thead>
          <tr>
            <th>Id Persona</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Inicio de vacaciones</th>
            <th>Dias Solicitados</th>
            <th>Tipo</th>
          </tr>
        </thead>

        <tbody>
          {% for item in object_list %}
          <tr>
            <td>{{item.personas.id_persona}}</td>
            <td>{{item.personas.nombre}}</td>
            <td>{{item.personas.apellido_paterno}} {{item.personas.apellido_materno}}</td>
            <td>{{item.fecha_inicio}}</td>
            <td>{{item.dias_tomados}}</td>
            <td>{{item.tipo}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/vacaciones/vacaciones_form.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Vacaciones</a>
  </li>
  <li class="breadcrumb-item active">Solicitud de vacaciones</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-users"></i>
    Formulario de vacaciones
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="form-group col-md-12">
          {{vacaciones.razon.label}}
          {{vacaciones.razon}}
        </div>

        <div class="form-group col-md-12">
          {{vacaciones.dias_tomados.label}}
          {{vacaciones.dias_tomados}}
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-12">
          {{vacaciones.fecha_inicio.label}}
          {{vacaciones.fecha_inicio}}
        </div>

        <div class="form-group col-md-12">
          {{vacaciones.observaciones.label}}
          {{vacaciones.observaciones}}
        </div>
      </div>

      <div class="row" hidden>
        <div class="form-group col-md-12" >
          {{vacaciones.id_solicitante.label}}
          <input type="text" name="id_solicitante" value="{{personas.id}}" class="form-control" readonly>
        </div>
      </div>

      <br>

      <div class="row">
        <div class="form-group col-md-4 ml-auto">
          <button type="submit" class="btn btn-success btn-block">Asignar vacaciones</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/vacaciones/vacaciones_list.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Listados</a>
  </li>
  <li class="breadcrumb-item active">Vacaciones Solicitadas</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header row">
    <div class="col-md-6"><i class="fa fa-table"></i> Listado de Vacaciones Solicitadas</div>

    <div class="col-md-6 offset-md-6"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><a href="{% url 'vacaciones:vacaciones_historial' %}"> Exportar a PDF</a></span></div>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      {% if not object_list %}
      <h4>No hay empleados registrados</h4>
      {% else  %}
      <table class="table table-bordered" width="100%" id="dataTable" cellspacing="0">
        <thead>
          <tr>
            <th>Id Persona</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Fecha de Inicio</th>
            <th>Dias Tomados</th>
            <th>Días Totales</th>
            <th>Dias Restantes</th>
          </tr>
        </thead>

        <tbody>
          {% for item in object_list %}
          <tr>
            <td>{{item.personas.id_persona}}</td>
            <td>{{item.personas.nombre}}</td>
            <td>{{item.personas.apellido_paterno}} {{item.personas.apellido_materno}}</td>
            <td>{{item.fecha_inicio}}</td>
            <td>{{item.dias_tomados}}</td>
            <td>{{item.dias_vacaciones}}</td>
            <td>{{item.dias_restantes}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}