HRMS/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout_then_login
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),
    url(r'^areas/', include('apps.areas.urls', namespace='areas')),
    url(r'^vacaciones/', include('apps.vacaciones.urls', namespace='vacaciones')),
]

if settings.DEBUG is True:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/personas/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url, include
from apps.personas.views import PersonaCreate, PersonaList, PersonaUpdate, PersonaDelete, PersonaInfo,\
PersonaInicio, PersonaFormato, PersonaListInactive, PersonaInactivePdf, PersonaFormatoBaja

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^inicio_persona$', login_required(PersonaInicio), name='inicio_persona'),
    url(r'^nueva_persona$', login_required(PersonaCreate.as_view()), name='nueva_persona'),
    url(r'^listado_persona$', login_required(PersonaList.as_view()), name='listado_persona'), #activos
    url(r'^baja_persona$', login_required(PersonaListInactive.as_view()), name='baja_persona'), #inactivos
    url(r'^baja_list$', login_required(PersonaInactivePdf), name='baja_list'), #inactivosPDF
    url(r'^info_persona/(?P<pk>\d+)$', login_required(PersonaInfo), name='info_persona'),
    url(r'^persona_formato/(?P<pk>\d+)$', login_required(PersonaFormato), name='persona_formato'),
    url(r'^persona_formato_baja/(?P<pk>\d+)$', login_required(PersonaFormatoBaja), name='persona_formato_baja'), #PDF
    # url(r'^vacaciones_hist/(?P<pk>\d+)$', PersonaVacacionesHist, name='vacaciones_hist'),
    # url(r'^persona_vacaciones/(?P<pk>\d+)$', login_required(PersonaVacaciones), name='persona_vacaciones'),
    url(r'^editar_persona/(?P<pk>\d+)$', login_required(PersonaUpdate.as_view()), name='editar_persona'),
    url(r'^eliminar_persona/(?P<pk>\d+)$', login_required(PersonaDelete.as_view()), name='eliminar_persona'),
]

apps/vacaciones/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url, include
from apps.vacaciones.views import AsignaVacaciones, VacacionesPersona, AsignaPermisos, PersonaVacacionesHist,\
PersonaPermisosHist, VacacionesList, PermisosList, VacacionesHist, PermisosHist

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^asignar_vacaciones/(?P<pk>\d+)$', login_required(AsignaVacaciones), name='asignar_vacaciones'),
    url(r'^info_persona/(?P<pk>\d+)$', login_required(VacacionesPersona), name='info_persona'),
    url(r'^vacaciones_hist/(?P<pk>\d+)$', login_required(PersonaVacacionesHist), name='vacaciones_hist'),
    url(r'^vacaciones_list$', login_required(VacacionesList.as_view()), name='vacaciones_list'),
    url(r'^vacaciones_historial$', login_required(VacacionesHist), name='vacaciones_historial'),

    #Permisos
    url(r'^asignar_permisos/(?P<pk>\d+)$', login_required(AsignaPermisos), name='asignar_permisos'),
    url(r'^permisos_hist/(?P<pk>\d+)$', login_required(PersonaPermisosHist), name='permisos_hist'),
    url(r'^permisos_list$', login_required(PermisosList.as_view()), name='permisos_list'),
    url(r'^permisos_historial$', login_required(PermisosHist), name='permisos_historial'),
]

apps/personas/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import models
from apps.areas.models import Area

import datetime

# Create your models here.

class Persona(models.Model):
    opciones = [('masculino', 'Masculino'), ('femenino', 'Femenino')]
    bajas = [('Renuncia', 'Renuncia'), ('Despido', 'Despido'), ('Jubilación', 'Jubilacion')]
    status = [('Activo', 'Activo'), ('Inactivo', 'Inactivo')]

    imagen = models.ImageField(upload_to='usr/', blank=True, null=True)
    nombre = models.CharField(max_length=30)
    apellido_paterno = models.CharField(max_length=30)
    apellido_materno = models.CharField(max_length=30)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    curp = models.CharField(max_length=18)
    rfc = models.CharField(max_length=18)
    sexo = models.CharField(max_length=70, choices=opciones)
    #datos de domicilio
    calle = models.CharField(max_length=40)
    numero_interior = models.IntegerField(blank=True, null=True)
    numero_exterior = models.IntegerField(blank=True, null=True)
    colonia = models.CharField(max_length=40)
    codigo_postal = models.IntegerField()
    pais = models.CharField(max_length=40)
    estado = models.CharField(max_length=40)
    municipio = models.CharField(max_length=40)
    #datos de contacto
    telefono = models.CharField(max_length=13)
    celular = models.CharField(max_length=13)
    correo = models.EmailField()
    #adicionales
    datos_adicionales = models.TextField(blank=True, null=True)
    id_persona = models.CharField(max_length=13)
    fecha_ingreso = models.DateField()
    activo = models.CharField(max_length = 40, choices=status, default='Activo')
    #datos baja
    fecha_baja = models.DateField(null=True, blank=True)
    motivo_baja = models.CharField(max_length=40, null=True, blank=True, choices=bajas)
    observaciones = models.CharField(max_length=40, null=True, blank=True)

    #llaves foraneas
    areas = models.ForeignKey(Area, blank=True, null=True)
    cargo = models.CharField(max_length=75)

    def __unicode__(self):
        return self.id_persona

    def __get__dias(self):
        today = datetime.date.today()
        ingreso = self.fecha_ingreso

        return (today.year - ingreso.year)*10

    def __get__antiguedad(self):
        today = datetime.date.today()
        ingreso = self.fecha_ingreso

        return (today.year - ingreso.year)

    vacaciones = property(__get__dias)
    antiguedad = property(__get__antiguedad)

apps/personas/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django import forms

from apps.personas.models import Persona

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona

        fields = [
            'imagen',
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'fecha_nacimiento',
            'curp',
            'rfc',
            'sexo',
            'calle',
            'numero_interior',
            'numero_exterior',
            'colonia',
            'codigo_postal',
            'pais',
            'estado',
            'municipio',
            'telefono',
            'celular',
            'correo',
            'datos_adicionales',
            'areas',
            'cargo',
            'fecha_ingreso',
            'id_persona',
            'fecha_baja',
            'motivo_baja',
            'observaciones',
            'activo',
        ]

        labels = {
            'imagen':'Imagen',
            'nombre':'Nombre',
            'apellido_paterno':'Apellido paterno',
            'apellido_materno':'Apellido materno',
            'fecha_nacimiento':'Fecha de nacimiento',
            'curp':'CURP',
            'rfc':'RFC',
            'sexo':'Sexo',
            'calle':'Calle',
            'numero_interior':'Número interior',
            'numero_exterior':'Número exterior',
            'colonia':'Colonia',
            'codigo_postal':'Codigo postal',
            'pais':'País',
            'estado':'Estado',
            'municipio':'Municipio',
            'telefono':'Teléfono',
            'celular':'Celular',
            'correo':'Correo',
            'datos_adicionales':'Datos adicionales',
            'areas':'Area',
            'cargo':'Cargo',
            'fecha_ingreso':'Fecha de Ingreso',
            'id_persona':'Id Empleado',
            'fecha_baja': 'Fecha de Baja',
            'motivo_baja': 'Motivo de Baja',
            'observaciones': 'Observaciones',
            'activo': 'Estatus',
        }

        widgets = {
            'imagen': forms.FileInput,
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'apellido_paterno': forms.TextInput(attrs={'class':'form-control'}),
            'apellido_materno': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_nacimiento': forms.TextInput(attrs={'class':'form-control'}),
            'curp': forms.TextInput(attrs={'class':'form-control'}),
            'rfc': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.Select(attrs={'class':'form-control'}),
            'calle': forms.TextInput(attrs={'class':'form-control'}),
            'numero_interior': forms.TextInput(attrs={'class':'form-control'}),
            'numero_exterior': forms.TextInput(attrs={'class':'form-control'}),
            'colonia': forms.TextInput(attrs={'class':'form-control'}),
            'codigo_postal': forms.TextInput(attrs={'class':'form-control'}),
            'pais': forms.TextInput(attrs={'class':'form-control'}),
            'estado': forms.TextInput(attrs={'class':'form-control'}),
            'municipio': forms.TextInput(attrs={'class':'form-control'}),
            'telefono': forms.TextInput(attrs={'class':'form-control'}),
            'celular': forms.TextInput(attrs={'class':'form-control'}),
            'correo': forms.TextInput(attrs={'class':'form-control'}),
            'datos_adicionales': forms.Textarea(attrs={'class':'form-control'}),
            'areas': forms.Select(attrs={'class':'form-control'}),
            'cargo':forms.TextInput(attrs={'class':'form-control'}),
            'fecha_ingreso':forms.TextInput(attrs={'class':'form-control'}),
            'id_persona': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_baja': forms.TextInput(attrs={'class':'form-control'}),
            'motivo_baja': forms.Select(attrs={'class':'form-control'}),
            'observaciones': forms.Textarea(attrs={'class':'form-control'}),
            'activo': forms.Select(attrs={'class':'form-control'}),
        }

apps/personas/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

import pdfkit
from django.template.loader import render_to_string

from django.shortcuts import render
from io import BytesIO

from reportlab.pdfgen import canvas

from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView
from reportlab.platypus import SimpleDocTemplate, Paragraph, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Table

from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
# from django.shortcuts import render

from apps.personas.models import Persona
from apps.personas.forms import PersonaForm

from apps.vacaciones.models import Vacaciones, Permisos

# Create your views here.
#Clases

class PersonaCreate(CreateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'personas/persona_form.html'
    success_url = reverse_lazy('personas:listado_persona')


class PersonaList(ListView):
    model = Persona
    template_name = 'personas/persona_list.html'

    def get_queryset(self):
        queryset = super(PersonaList, self).get_queryset()
        return queryset.filter(activo='Activo')


class PersonaListInactive(ListView):
    model = Persona
    template_name = 'personas/persona_baja_list.html'

    def get_queryset(self):
        queryset = super(PersonaListInactive, self).get_queryset()
        return queryset.filter(activo='Inactivo')


class PersonaUpdate(UpdateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'personas/persona_edit.html'
    success_url = reverse_lazy('personas:listado_persona')

    def get_context_data(self, **kwargs):
        context = super(PersonaUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk',0)
        persona = self.model.objects.get(id=pk)
        if 'form' not in context:
            context['form'] = self.form_class()
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_personas = kwargs['pk']
        personas = self.model.objects.get(id=id_personas)
        form = self.form_class(request.POST, instance=personas)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

class PersonaDelete(UpdateView):
    model = Persona
    form_class = PersonaForm
    template_name = 'personas/persona_delete.html'
    success_url = reverse_lazy('personas:listado_persona')

    def get_context_data(self, **kwargs):
        context = super(PersonaDelete, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk',0)
        persona = self.model.objects.get(id=pk)
        if 'form' not in context:
            context['form'] = self.form_class()
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_personas = kwargs['pk']
        personas = self.model.objects.get(id=id_personas)
        form = self.form_class(request.POST, instance=personas)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

def PersonaInactivePdf(request):
    personas = Persona.objects.all().filter(activo='Inactivo')
    rendered = render_to_string('formatos/persona_bajas.html', {'personas':personas})
    # Create a URL of our project and go to the template route
    pdf = pdfkit.from_string(rendered, False)
    # Generate download
    response = HttpResponse(pdf, content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response

#Funciones
def PersonaInicio(request):
    context = {}
    return render(request, 'personas/persona_inicio.html', context)

def PersonaInfo(request, pk):
    personas = Persona.objects.get(id=pk)
    vacaciones = Vacaciones.objects.all().filter(id_solicitante=pk)
    permisos = Permisos.objects.all().filter(id_solicitante=pk)
    context = {'personas':personas, 'vacaciones':vacaciones, 'permisos':permisos}
    return render(request, 'personas/persona_info.html', context)


def PersonaFormato(request, pk):
    personas = Persona.objects.all().filter(id=pk)
    rendered = render_to_string('formatos/formato_alta.html', {'personas':personas})
    # Create a URL of our project and go to the template route
    pdf = pdfkit.from_string(rendered, False)
    # Generate download
    response = HttpResponse(pdf, content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response

def PersonaFormatoBaja(request, pk):
    personas = Persona.objects.all().filter(id=pk)
    rendered = render_to_string('formatos/formato_baja.html', {'personas':personas})
    # Create a URL of our project and go to the template route
    pdf = pdfkit.from_string(rendered, False)
    # Generate download
    response = HttpResponse(pdf, content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response

def PersonaVacacionesHist(request, pk):
    vacaciones = Vacaciones.objects.all().filter(id_solicitante=pk)
    personas = Persona.objects.all().filter(id=pk)
    rendered = render_to_string('formatos/vacaciones_hist.html', {'personas':personas, 'vacaciones':vacaciones})
    # Create a URL of our project and go to the template route
    pdf = pdfkit.from_string(rendered, False)
    # Generate download
    response = HttpResponse(pdf, content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="ourcodeworld.pdf"'

    return response

templates/personas/persona_baja_list.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Listados</a>
  </li>
  <li class="breadcrumb-item active">Historial de Bajas</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header row">
    <div class="col-md-6"><i class="fa fa-table"></i>Listado de personal</div>
    <div class="col-md-6 offset-md-6"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><a href="{% url 'personas:baja_list' %}"> Exportar a PDF</a></span></div>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      {% if not object_list %}
      <h4>No hay empleados registrados</h4>
      {% else  %}
      <table class="table table-bordered" width="100%" id="dataTable" cellspacing="0">
        <thead>
          <tr>
            <th>Id Persona</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Fecha de Ingreso</th>
            <th>Fecha de Baja</th>
            <th>Estatus</th>
            <th>Exportar a PDF</th>
          </tr>
        </thead>

        <tbody>
          {% for item in object_list %}
          <tr>
            <td>{{item.id_persona}}</td>
            <td>{{item.nombre}}</td>
            <td>{{item.apellido_paterno}} {{item.apellido_materno}}</td>
            <td>{{item.fecha_ingreso}}</td>
            <td>{{item.fecha_baja}}</td>
            <td>{{item.activo}}</td>
            <td><a href="{% url 'personas:persona_formato_baja' item.id %}" class="btn btn-success">Formato</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/personas/persona_delete.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-times"></i>
    Eliminar Empleado
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}
      <div>
        <div class="form-group" hidden>
          {{form.as_p}}
        </div>

        <div class="form-group">
          {{form.fecha_baja.label}}
          {{form.fecha_baja}}
        </div>

        <div class="form-group">
          {{form.motivo_baja.label}}
          {{form.motivo_baja}}
        </div>

        <div class="form-group">
          {{form.observaciones.label}}
          {{form.observaciones}}
        </div>

        <div class="form-group">
          {{form.activo.label}}
          {{form.activo}}
        </div>
        <button type="submit" class="btn btn-danger">SI, Eliminar</button>
        <a class="btn btn-success" href="{% url 'personas:listado_persona' %}">Cancelar</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/personas/persona_edit.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="card mb-3">
  {# <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt explicabo vero veritatis ab fugit? Excepturi, illum possimus? Sunt, nobis consequatur sapiente repellendus soluta sed corrupti doloremque adipisci non, officiis in?</span>#}
  <div class="card-header">
    <i class="fa fa-users"></i>
    Formulario de altas
  </div>
  <div class="card-body">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- <div class="row">
        <div class="form-group col-md-3">
          {{form.nombre.label}}
          {{form.nombre}}
        </div>

        <div class="form-group col-md-3">
          {{form.apellido_paterno.label}}
          {{form.apellido_paterno}}
        </div>

        <div class="form-group col-md-3">
          {{form.apellido_materno.label}}
          {{form.apellido_materno}}
        </div>

        <div class="form-group col-md-3">
          {{form.sexo.label}}
          {{form.sexo}}
        </div>
      </div>#}

      {# <div class="row">
        <div class="form-group col-md-3">
          {{form.fecha_nacimiento.label}}
          {{form.fecha_nacimiento}}
        </div>

        <div class="form-group col-md-3">
          {{form.curp.label}}
          {{form.curp}}
        </div>

        <div class="form-group col-md-3">
          {{form.rfc.label}}
          {{form.rfc}}
        </div>
      </div>#}

      {# Domiciliarios #}
      {# <div class="row">
        <div class="form-group col-md-3">
          {{form.calle.label}}
          {{form.calle}}
        </div>

        <div class="form-group col-md-3">
          {{form.numero_interior.label}}
          {{form.numero_interior}}
        </div>

        <div class="form-group col-md-3">
          {{form.numero_exterior.label}}
          {{form.numero_exterior}}
        </div>

        <div class="form-group col-md-3">
          {{form.colonia.label}}
          {{form.colonia}}
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-3">
          {{form.codigo_postal.label}}
          {{form.codigo_postal}}
        </div>

        <div class="form-group col-md-3">
          {{form.pais.label}}
          {{form.pais}}
        </div>

        <div class="form-group col-md-3">
          {{form.estado.label}}
          {{form.estado}}
        </div>

        <div class="form-group col-md-3">
          {{form.municipio.label}}
          {{form.municipio}}
        </div>
      </div>#}

      {# Contacto #}
      {# <div class="row">
        <div class="form-group col-md-3">
          {{form.telefono.label}}
          {{form.telefono}}
        </div>

        <div class="form-group col-md-3">
          {{form.celular.label}}
          {{form.celular}}
        </div>

        <div class="form-group col-md-3">
          {{form.correo.label}}
          {{form.correo}}
        </div>
      </div>#}

      {# Puesto #}
      {# <div class="row">
        <div class="form-group col-md-3">
          {{form.areas.label}}
          {{form.areas}}
        </div>

        <div class="form-group col-md-3">
          {{form.cargo.label}}
          {{form.cargo}}
        </div>

        <div class="form-group col-md-3">
          {{form.id_persona.label}}
          {{form.id_persona}}
        </div>

        <div class="form-group col-md-3">
          {{form.fecha_ingreso.label}}
          {{form.fecha_ingreso}}
        </div>
      </div> -->

      {{ form.as_p }}

      <br>
      <div class="row">
        <div class="form-group col-md-4 ml-auto">
          <button type="submit" class="btn btn-success btn-block">Guardar cambios</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/personas/persona_inicio.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Bienvenido</a>
  </li>
  <li class="breadcrumb-item active">inicio</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-address-card"></i>
    Inicio
  </div>
  <div class="card-body text-center">
    <h1 style="font-size: 5em">Bienvenid@!!</h1>
    <h1>{{user.first_name}} {{user.last_name}}</h1>
  </div>
</div>
{% endblock %}

templates/personas/persona_list.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Listado de Personal</a>
  </li>
  <li class="breadcrumb-item active">Listado</li>
</ol>
{% endblock %}

{% block content %}
<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-table"></i>
    Listado de personal
  </div>
  <div class="card-body">
    <div class="table-responsive">
      {% if not object_list %}
      <h4>No hay empleados registrados</h4>
      {% else  %}
      <table class="table table-bordered" width="100%" id="dataTable" cellspacing="0">
        <thead>
          <tr>
            <th>Id Persona</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Fecha de Ingreso</th>
            <th>Area</th>
            <th>Opciones</th>
            <th>Formatos</th>
          </tr>
        </thead>

        <tbody>
          {% for item in object_list %}
          <tr>
          <td>{{item.id_persona}}</td>
          <td>{{item.nombre}}</td>
          <td>{{item.apellido_paterno}} {{item.apellido_materno}}</td>
          <td>{{item.fecha_ingreso}}</td>
          <td>{{item.areas.nombre_area}}</td>
          <td>
            <div class="dropdown show">
              <div class="dropdown">
                <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Opciones
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'personas:info_persona' item.id %}">Información de {{item.nombre}} {{item.apellido_paterno}}</a>
                  <a class="dropdown-item" href="{% url 'vacaciones:asignar_vacaciones' item.id %}">Asignar Vacaciones</a>
                  <a class="dropdown-item" href="{% url 'vacaciones:asignar_permisos' item.id %}">Asignar Permisos</a>
                  <a class="dropdown-item" href="{% url 'personas:editar_persona' item.id %}">Editar</a>
                  <a class="dropdown-item" href="{% url 'personas:eliminar_persona' item.id %}">Eliminar</a>
                </div>
              </div>
            </div>
          </td>
          <td>
            <div class="dropdown show">
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Formatos
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'personas:persona_formato' item.id %}">Formato de alta</a>
                  <a class="dropdown-item" href="">Formato de baja</a>
                  <a class="dropdown-item" href="{% url 'vacaciones:vacaciones_hist' item.id %}">Historial de vacaciones</a>
                  <a class="dropdown-item" href="{% url 'vacaciones:permisos_hist' item.id %}">Historial de permisos</a>

                </div>
              </div>
            </div>
          </td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}